### PR TITLE
BUG: Program crashed when markers were close to the image border.

### PR DESCRIPTION
**Pull request by zivy**
Refactored the logic behind the ROI selection. We now take a fixed
sized ROI centered on the marker point and interesect it with the
image to get the final ROI which is used in the registration. Also
modified ther registration initialization so that it aligns the fixed
and moving markers even if they are not in the center of the ROI
(which is what happens when they are close to the image border).

### CODE REVIEW

**Comment by blowekamp** [comment]
I tried this fix and it helps me with the data set I was working on too! Thanks!

**Comment by blowekamp** [comment]
@pieper @jcfr May I move this patch through and update Slicer?

**Comment by jcfr** [comment]
@zivy  Thanks for the contribution :+1: 

@pieper When you have a chance, could you review and integrate ?

**Comment by pieper** [comment]
Thanks for the fix!  Sorry for the slow reply - was traveling last week and now getting ready for RSNA 😄

**Comment by pieper** [comment]
I'll update the Slicer superbuild with this commit.

**Comment by zivy** [comment]
@pieper Thanks. 

Once it is merged I won't have to worry about deleting/overwriting my current Slicer installation which I fixed for myself (I've lost work in the past where I fixed/patched something locally for myself and later overwrote it with a software update).
Happy thanksgiving, 🦃 .

**Comment by jcfr** [comment]
:+1

**Comment by zivy** [comment]
I did experience that behavior (problem "grabbing" fiducials) but it appears that if I : (a) lock the window/level for the volumes (b) zoom in on the fiducials I can grab them.
I wasn't sure if this is a feature or bug so didn't complain about it.

**Comment by pieper** [comment]
Interesting clue - thanks!  I don't think locking the window level is required (but I can see why it helps avoid unintended consequences).

What works for me is not zooming, but panning so that the fiducial is not in the exact center of the viewport.  This kind of makes sense if the picking bug is due to invisible widgets that happen to be at the origin.  This isn't a solution, but it seems like a reliable workaround.

**Pull request merged**
